### ISSUE TITLE
Installing with npm results in deprecation warnings

### ISSUE THREAD

**Issue by lukeh990** [discordjs/discord-api-types#233]
**Please describe the problem you are having in as much detail as possible:**
When I install the discord-api-types package with the command `npm install discord.js @discordjs/rest discord-api-types` I get the following warnings:
```
npm WARN deprecated @sapphire/snowflake@1.3.6: This version has been automatically deprecated by @favware/npm-deprecate. Please use a newer version.
npm WARN deprecated discord-api-types@0.18.1: No longer supported. Install the latest release (0.20.2)
```
In the `package.json` the following entries are added:
```json
"dependencies": {
    "@discordjs/rest": "^0.1.0-canary.0",
    "discord-api-types": "^0.24.0",
    "discord.js": "^13.3.1"
}
```
**Further details:**

- Runtime:
  
  - Node.js version: v17.0.1
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Comment by ImRodry** [comment]
This is because @discordjs/rest hasn't been updated in a while and the latest release has those outdated deps. I believe this has been fixed on the repo but a release hasn't been pushed yet. You can safely ignore the discord-api-types warning because when installing the package itself you're installing the latest version automatically

**Comment by vladfrangu** [comment]
This isn't an issue with this module but with our rest package being outdated
